mv fasta/bacteria_0_collection/*/dna/* single_files/.
mv fasta/bacteria_1_collection/*/dna/* single_files/.
mv fasta/bacteria_2_collection/*/dna/* single_files/.
mv fasta/bacteria_3_collection/*/dna/* single_files/.
mv fasta/bacteria_4_collection/*/dna/* single_files/.
mv fasta/bacteria_5_collection/*/dna/* single_files/.
mv fasta/bacteria_6_collection/*/dna/* single_files/.
mv fasta/bacteria_7_collection/*/dna/* single_files/.
mv fasta/bacteria_8_collection/*/dna/* single_files/.
mv fasta/bacteria_9_collection/*/dna/* single_files/.
mv fasta/bacteria_10_collection/*/dna/* single_files/.
mv fasta/bacteria_11_collection/*/dna/* single_files/.
mv fasta/bacteria_12_collection/*/dna/* single_files/.
mv fasta/bacteria_13_collection/*/dna/* single_files/.
mv fasta/bacteria_14_collection/*/dna/* single_files/.
mv fasta/bacteria_15_collection/*/dna/* single_files/.
mv fasta/bacteria_16_collection/*/dna/* single_files/.
mv fasta/bacteria_17_collection/*/dna/* single_files/.
mv fasta/bacteria_18_collection/*/dna/* single_files/.
mv fasta/bacteria_19_collection/*/dna/* single_files/.
mv fasta/bacteria_20_collection/*/dna/* single_files/.
mv fasta/bacteria_21_collection/*/dna/* single_files/.
mv fasta/bacteria_22_collection/*/dna/* single_files/.
mv fasta/bacteria_23_collection/*/dna/* single_files/.
mv fasta/bacteria_24_collection/*/dna/* single_files/.
mv fasta/bacteria_25_collection/*/dna/* single_files/.
mv fasta/bacteria_26_collection/*/dna/* single_files/.
mv fasta/bacteria_27_collection/*/dna/* single_files/.
mv fasta/bacteria_28_collection/*/dna/* single_files/.
mv fasta/bacteria_29_collection/*/dna/* single_files/.
mv fasta/bacteria_30_collection/*/dna/* single_files/.
mv fasta/bacteria_31_collection/*/dna/* single_files/.
mv fasta/bacteria_32_collection/*/dna/* single_files/.
mv fasta/bacteria_33_collection/*/dna/* single_files/.
mv fasta/bacteria_34_collection/*/dna/* single_files/.
mv fasta/bacteria_35_collection/*/dna/* single_files/.
mv fasta/bacteria_36_collection/*/dna/* single_files/.
mv fasta/bacteria_37_collection/*/dna/* single_files/.
mv fasta/bacteria_38_collection/*/dna/* single_files/.
mv fasta/bacteria_39_collection/*/dna/* single_files/.
mv fasta/bacteria_40_collection/*/dna/* single_files/.
mv fasta/bacteria_41_collection/*/dna/* single_files/.
mv fasta/bacteria_42_collection/*/dna/* single_files/.
mv fasta/bacteria_43_collection/*/dna/* single_files/.
mv fasta/bacteria_44_collection/*/dna/* single_files/.
mv fasta/bacteria_45_collection/*/dna/* single_files/.
mv fasta/bacteria_46_collection/*/dna/* single_files/.
mv fasta/bacteria_47_collection/*/dna/* single_files/.
mv fasta/bacteria_48_collection/*/dna/* single_files/.
mv fasta/bacteria_49_collection/*/dna/* single_files/.
mv fasta/bacteria_50_collection/*/dna/* single_files/.
mv fasta/bacteria_51_collection/*/dna/* single_files/.
mv fasta/bacteria_52_collection/*/dna/* single_files/.
mv fasta/bacteria_53_collection/*/dna/* single_files/.
mv fasta/bacteria_54_collection/*/dna/* single_files/.
mv fasta/bacteria_55_collection/*/dna/* single_files/.
mv fasta/bacteria_56_collection/*/dna/* single_files/.
mv fasta/bacteria_57_collection/*/dna/* single_files/.
mv fasta/bacteria_58_collection/*/dna/* single_files/.
mv fasta/bacteria_59_collection/*/dna/* single_files/.
mv fasta/bacteria_60_collection/*/dna/* single_files/.
mv fasta/bacteria_61_collection/*/dna/* single_files/.
mv fasta/bacteria_62_collection/*/dna/* single_files/.
mv fasta/bacteria_63_collection/*/dna/* single_files/.
mv fasta/bacteria_64_collection/*/dna/* single_files/.
mv fasta/bacteria_65_collection/*/dna/* single_files/.
mv fasta/bacteria_66_collection/*/dna/* single_files/.
mv fasta/bacteria_67_collection/*/dna/* single_files/.
mv fasta/bacteria_68_collection/*/dna/* single_files/.
mv fasta/bacteria_69_collection/*/dna/* single_files/.
mv fasta/bacteria_70_collection/*/dna/* single_files/.
mv fasta/bacteria_71_collection/*/dna/* single_files/.
mv fasta/bacteria_72_collection/*/dna/* single_files/.
mv fasta/bacteria_73_collection/*/dna/* single_files/.
mv fasta/bacteria_74_collection/*/dna/* single_files/.
mv fasta/bacteria_75_collection/*/dna/* single_files/.
mv fasta/bacteria_76_collection/*/dna/* single_files/.
mv fasta/bacteria_77_collection/*/dna/* single_files/.
mv fasta/bacteria_78_collection/*/dna/* single_files/.
mv fasta/bacteria_79_collection/*/dna/* single_files/.
mv fasta/bacteria_80_collection/*/dna/* single_files/.
mv fasta/bacteria_81_collection/*/dna/* single_files/.
mv fasta/bacteria_82_collection/*/dna/* single_files/.
mv fasta/bacteria_83_collection/*/dna/* single_files/.
mv fasta/bacteria_84_collection/*/dna/* single_files/.
mv fasta/bacteria_85_collection/*/dna/* single_files/.
mv fasta/bacteria_86_collection/*/dna/* single_files/.
mv fasta/bacteria_87_collection/*/dna/* single_files/.
mv fasta/bacteria_88_collection/*/dna/* single_files/.
mv fasta/bacteria_89_collection/*/dna/* single_files/.
mv fasta/bacteria_90_collection/*/dna/* single_files/.
mv fasta/bacteria_91_collection/*/dna/* single_files/.
mv fasta/bacteria_92_collection/*/dna/* single_files/.
mv fasta/bacteria_93_collection/*/dna/* single_files/.
mv fasta/bacteria_94_collection/*/dna/* single_files/.
mv fasta/bacteria_95_collection/*/dna/* single_files/.
mv fasta/bacteria_96_collection/*/dna/* single_files/.
mv fasta/bacteria_97_collection/*/dna/* single_files/.
mv fasta/bacteria_98_collection/*/dna/* single_files/.
mv fasta/bacteria_99_collection/*/dna/* single_files/.
mv fasta/bacteria_100_collection/*/dna/* single_files/.
mv fasta/bacteria_101_collection/*/dna/* single_files/.
mv fasta/bacteria_102_collection/*/dna/* single_files/.
mv fasta/bacteria_103_collection/*/dna/* single_files/.
mv fasta/bacteria_104_collection/*/dna/* single_files/.
mv fasta/bacteria_105_collection/*/dna/* single_files/.
mv fasta/bacteria_106_collection/*/dna/* single_files/.
mv fasta/bacteria_107_collection/*/dna/* single_files/.
mv fasta/bacteria_108_collection/*/dna/* single_files/.
mv fasta/bacteria_109_collection/*/dna/* single_files/.
mv fasta/bacteria_110_collection/*/dna/* single_files/.
mv fasta/bacteria_111_collection/*/dna/* single_files/.
mv fasta/bacteria_112_collection/*/dna/* single_files/.
mv fasta/bacteria_113_collection/*/dna/* single_files/.
mv fasta/bacteria_114_collection/*/dna/* single_files/.
mv fasta/bacteria_115_collection/*/dna/* single_files/.
mv fasta/bacteria_116_collection/*/dna/* single_files/.
mv fasta/bacteria_117_collection/*/dna/* single_files/.
mv fasta/bacteria_118_collection/*/dna/* single_files/.
mv fasta/bacteria_119_collection/*/dna/* single_files/.
mv fasta/bacteria_120_collection/*/dna/* single_files/.
mv fasta/bacteria_121_collection/*/dna/* single_files/.
mv fasta/bacteria_122_collection/*/dna/* single_files/.
mv fasta/bacteria_123_collection/*/dna/* single_files/.
mv fasta/bacteria_124_collection/*/dna/* single_files/.
mv fasta/bacteria_125_collection/*/dna/* single_files/.
mv fasta/bacteria_126_collection/*/dna/* single_files/.
mv fasta/bacteria_127_collection/*/dna/* single_files/.
mv fasta/bacteria_128_collection/*/dna/* single_files/.
mv fasta/bacteria_129_collection/*/dna/* single_files/.
mv fasta/bacteria_130_collection/*/dna/* single_files/.
mv fasta/bacteria_131_collection/*/dna/* single_files/.
mv fasta/bacteria_132_collection/*/dna/* single_files/.
mv fasta/bacteria_133_collection/*/dna/* single_files/.
mv fasta/bacteria_134_collection/*/dna/* single_files/.
mv fasta/bacteria_135_collection/*/dna/* single_files/.
mv fasta/bacteria_136_collection/*/dna/* single_files/.
mv fasta/bacteria_137_collection/*/dna/* single_files/.
mv fasta/bacteria_138_collection/*/dna/* single_files/.
mv fasta/bacteria_139_collection/*/dna/* single_files/.
mv fasta/bacteria_140_collection/*/dna/* single_files/.
mv fasta/bacteria_141_collection/*/dna/* single_files/.
mv fasta/bacteria_142_collection/*/dna/* single_files/.
mv fasta/bacteria_143_collection/*/dna/* single_files/.
mv fasta/bacteria_144_collection/*/dna/* single_files/.
mv fasta/bacteria_145_collection/*/dna/* single_files/.
mv fasta/bacteria_146_collection/*/dna/* single_files/.
mv fasta/bacteria_147_collection/*/dna/* single_files/.
mv fasta/bacteria_148_collection/*/dna/* single_files/.
mv fasta/bacteria_149_collection/*/dna/* single_files/.
mv fasta/bacteria_150_collection/*/dna/* single_files/.
mv fasta/bacteria_151_collection/*/dna/* single_files/.
mv fasta/bacteria_152_collection/*/dna/* single_files/.
mv fasta/bacteria_153_collection/*/dna/* single_files/.
mv fasta/bacteria_154_collection/*/dna/* single_files/.
mv fasta/bacteria_155_collection/*/dna/* single_files/.
mv fasta/bacteria_156_collection/*/dna/* single_files/.
mv fasta/bacteria_157_collection/*/dna/* single_files/.
mv fasta/bacteria_158_collection/*/dna/* single_files/.
mv fasta/bacteria_159_collection/*/dna/* single_files/.
mv fasta/bacteria_160_collection/*/dna/* single_files/.
mv fasta/bacteria_161_collection/*/dna/* single_files/.
mv fasta/bacteria_162_collection/*/dna/* single_files/.
mv fasta/bacteria_163_collection/*/dna/* single_files/.
mv fasta/bacteria_164_collection/*/dna/* single_files/.
mv fasta/bacteria_165_collection/*/dna/* single_files/.
mv fasta/bacteria_166_collection/*/dna/* single_files/.
mv fasta/bacteria_167_collection/*/dna/* single_files/.
mv fasta/bacteria_168_collection/*/dna/* single_files/.
mv fasta/bacteria_169_collection/*/dna/* single_files/.
mv fasta/bacteria_170_collection/*/dna/* single_files/.
mv fasta/bacteria_171_collection/*/dna/* single_files/.
mv fasta/bacteria_172_collection/*/dna/* single_files/.
mv fasta/bacteria_173_collection/*/dna/* single_files/.
mv fasta/bacteria_174_collection/*/dna/* single_files/.
mv fasta/bacteria_175_collection/*/dna/* single_files/.
mv fasta/bacteria_176_collection/*/dna/* single_files/.
mv fasta/bacteria_177_collection/*/dna/* single_files/.
mv fasta/bacteria_178_collection/*/dna/* single_files/.
mv fasta/bacteria_179_collection/*/dna/* single_files/.
mv fasta/bacteria_180_collection/*/dna/* single_files/.
mv fasta/bacteria_181_collection/*/dna/* single_files/.
mv fasta/bacteria_182_collection/*/dna/* single_files/.
mv fasta/bacteria_183_collection/*/dna/* single_files/.
